import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <div className="main">{children}</div>
          <div className="userProfile_section">
            <div className="profile">
              <Image src="/profile.png" alt="Profile" width={60} height={60} />
              <h2>User name</h2>
            </div>
          </div>
          <div className="navigation_section">
            <ul>
              <li>
                <Link href="/">Home</Link>{" "}
              </li>
              <li>
                <Link href="/">Search</Link>{" "}
              </li>
              <li>
                <Link href="/post">Posts</Link>{" "}
              </li>
              <li>
                <Link href="/">Live</Link>{" "}
              </li>
            </ul>
            <button type="button">Logout</button>
          </div>
        </div>
      </body>
    </html>
  );
}
